version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:1.4.12
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - frontend
#    volumes:
#      - ./mosquitto/:/mosquitto/config/

  owmpub:
    image: owmpub-app
    build: ./owm-publisher
    networks:
      - frontend
#    volumes:
#      - ./owm-publisher.conf:/app/config/owm-publisher.conf

networks:
  frontend:
