version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:1.4.12
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - frontend
#    volumes:
#      - ./mosquitto/:/mosquitto/config/

  owmpub:
    image: owmpub-app
    build: ./owm-publisher
    restart: always
    networks:
      - frontend
    volumes:
      - ${PWD}/owm-publisher-conf/:/app/config/

networks:
  frontend:
